spring.application.name=Resume-Analyzer

# Server Port
server.port=8081

# Database Configuration
# Database Configuration
spring.datasource.url=jdbc:postgresql://ep-muddy-scene-aqnxm1mr-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_i7QDcp0hGRlU
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
